language: r
cache: packages
r: release

env:
    - BIODB_USERAGENT="biodbKegg.test ; pierrick.roger@cea.fr"

notifications:
    email:
        recipients:
            - pierrick.roger@cea.fr

branches:
  only:
    - master

before_install:
    - sudo apt-get install -y libmagick++-dev
    - R -e 'install.packages("BiocManager");BiocManager::install("BiocCheck")'
    - R -e 'install.packages("devtools", dependencies=TRUE)'
    - R -e 'devtools::install_github("pkrog/biodb", ref="master", dependencies=TRUE, build_vignettes=FALSE)'

script:
    - make check

after_success:
    - Rscript -e 'covr::codecov()'
